List1 = [
    [1000,
     2000,
     3000],

    [4000],

    [5000,
     6000],

    [7000,
     8000,
     9000],

    [10000]
]

# Solution
# generated by https://beta.openai.com/playground/p/sExWXFsXndEyYxdDBsjNIEMJ?model=text-davinci-003
def find_most_calories(food_list):
    most_calories = 0
    total_calories = 0
    elf_index = 0

    for i, elf in enumerate(food_list):
        for item in elf:
            total_calories += item
        if total_calories > most_calories:
            most_calories = total_calories
            elf_index = i
        total_calories = 0

    return elf_index, most_calories

elf_index, most_calories = find_most_calories(List1)

print(f"The Elf carrying the most Calories is Elf {elf_index + 1}, carrying {most_calories} Calories.")
